### ISSUE TITLE
[Bug] Uniqueness test on company_id in company history model

### ISSUE THREAD

**Issue by matthew-LL** [fivetran/dbt_intercom_source#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The `stg_intercom__company_history` model has a uniqueness test on `company_id`, however I have a encountered an error since `company_id` is not unique on the history table as a new row per company is added whenever the company is updated. This results in a `company_id` uniqueness test failure when building `stg_intercom__company_history`.

```
  - name: stg_intercom__company_history
    description: Table containing historical information about companies which have been created within Intercom.
    columns:
      - name: company_id
        description: The unique identifier representing the Intercom defined company.
        tests:
          - not_null
          - unique
```

### Expected behavior

I would expect primary key tests for `stg_intercom__company_history` to pass only if they were testing a surrogate key based off `company_id` and `updated_at`.

### dbt Project configurations

```  
intercom_database: raw_db
intercom_schema: fivetran_intercom
intercom__using_company_tags: false
```

### Package versions

```
  - package: fivetran/intercom_source
    version: [">=0.7.0", "<0.8.0"]
```

### What database are you using dbt with?

snowflake

### dbt Version

```
Core:
  - installed: 1.5.6
```

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
